import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    title: 'Rosewater Hydration Mask',
    slug: 'rosewater-hydration-mask',
    description: 'A deeply hydrating mask infused with pure rosewater.',
    longDescription:
      'Indulge your skin with our Rosewater Hydration Mask. This luxurious gel mask provides an instant boost of moisture, leaving your skin feeling soft, plump, and dewy. Formulated with pure rosewater to soothe irritation and hyaluronic acid to lock in hydration, it\'s a perfect treat for thirsty skin.',
    price: 2800,
    currency: 'INR',
    images: ['product-1'],
    ingredients: ['Rosewater', 'Hyaluronic Acid', 'Glycerin', 'Aloe Vera'],
    benefits: ['Deeply hydrates', 'Soothes and calms', 'Plumps skin'],
    skinTypes: ['dry', 'normal', 'combination'],
    tags: ['hydrating', 'organic'],
    stock: 150,
    rating: 4.8,
    reviewsCount: 112,
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Alice', rating: 5, title: 'Incredibly hydrating!', body: 'My dry skin drank this up. It feels so soft and looks so glowy after just one use.', createdAt: '2023-10-10' },
      { id: 'r2', userId: 'u2', userName: 'Bob', rating: 4, title: 'Smells amazing', body: 'The rose scent is beautiful and not overpowering. Very refreshing mask.', createdAt: '2023-10-12' },
    ],
  },
  {
    id: '2',
    title: 'Green Tea Detox Mask',
    slug: 'green-tea-detox-mask',
    description: 'Purify and refine your pores with this antioxidant-rich clay mask.',
    longDescription:
      'Our Green Tea Detox Mask is your solution for congested, oily skin. Powered by antioxidant-rich matcha green tea and clarifying bentonite clay, this mask works to draw out impurities, reduce excess oil, and minimize the appearance of pores for a smoother, more refined complexion.',
    price: 3200,
    currency: 'INR',
    images: ['product-2'],
    ingredients: ['Matcha Green Tea', 'Bentonite Clay', 'Witch Hazel', 'Tea Tree Oil'],
    benefits: ['Detoxifies and purifies', 'Minimizes pores', 'Controls oil'],
    skinTypes: ['oily', 'combination'],
    tags: ['vegan'],
    stock: 80,
    rating: 4.6,
    reviewsCount: 98,
    reviews: [
      { id: 'r3', userId: 'u3', userName: 'Charlie', rating: 5, title: 'Holy grail for oily skin!', body: 'This is the only mask that has ever controlled my oil without stripping my skin. I love it!', createdAt: '2023-09-20' },
    ],
  },
  {
    id: '3',
    title: 'Charcoal Exfoliating Scrub',
    slug: 'charcoal-exfoliating-scrub',
    description: 'A gentle scrub to polish away dead skin cells.',
    longDescription: 'Reveal a brighter, smoother complexion with our Charcoal Exfoliating Scrub. Fine bamboo particles and activated charcoal work in tandem to gently polish the skin, buffing away dead cells and impurities. The creamy formula rinses clean, leaving your skin feeling refreshed and renewed.',
    price: 2500,
    currency: 'INR',
    images: ['product-3'],
    ingredients: ['Activated Charcoal', 'Bamboo Powder', 'Jojoba Oil', 'Shea Butter'],
    benefits: ['Exfoliates dead skin', 'Brightens complexion', 'Unclogs pores'],
    skinTypes: ['oily', 'normal', 'combination'],
    tags: ['exfoliating'],
    stock: 200,
    rating: 4.7,
    reviewsCount: 150,
    reviews: [
       { id: 'r4', userId: 'u4', userName: 'Diana', rating: 5, title: 'So smooth!', body: 'My skin feels like a baby\'s bottom after using this. Not harsh at all.', createdAt: '2023-11-01' },
    ],
  },
  {
    id: '4',
    title: 'Vitamin C Brightening Mask',
    slug: 'vitamin-c-brightening-mask',
    description: 'Energize dull skin with a potent dose of Vitamin C.',
    longDescription: 'Wake up tired, lackluster skin with our Vitamin C Brightening Mask. This potent formula features a stable form of Vitamin C and turmeric extract to visibly brighten, even out skin tone, and diminish the look of dark spots. The result is a luminous, healthy-looking glow.',
    price: 3500,
    currency: 'INR',
    images: ['product-4'],
    ingredients: ['Vitamin C', 'Turmeric Extract', 'Kaolin Clay', 'Niacinamide'],
    benefits: ['Brightens and evens tone', 'Reduces dark spots', 'Boosts radiance'],
    skinTypes: ['normal', 'combination', 'dry'],
    tags: ['brightening', 'vegan'],
    stock: 120,
    rating: 4.9,
    reviewsCount: 210,
    reviews: [
       { id: 'r5', userId: 'u5', userName: 'Eve', rating: 5, title: 'Instant glow!', body: 'I use this before a big event and it makes my skin look incredible. Absolutely worth it.', createdAt: '2023-10-25' },
    ],
  },
  {
    id: '5',
    title: 'Soothing Lavender Sleep Mask',
    slug: 'soothing-lavender-sleep-mask',
    description: 'A calming overnight mask to soothe skin and mind.',
    longDescription: 'Drift off to sleep while this mask works its magic. Our Soothing Lavender Sleep Mask is a lightweight, leave-on treatment that deeply nourishes and calms sensitive or irritated skin. The relaxing scent of lavender helps you unwind, while ceramides and squalane work to repair your skin\'s moisture barrier overnight.',
    price: 3800,
    currency: 'INR',
    images: ['product-5'],
    ingredients: ['Lavender Oil', 'Ceramides', 'Squalane', 'Centella Asiatica'],
    benefits: ['Calms irritation', 'Repairs moisture barrier', 'Deeply nourishes'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    tags: ['hydrating', 'anti-aging'],
    stock: 90,
    rating: 4.8,
    reviewsCount: 134,
    reviews: [
       { id: 'r6', userId: 'u6', userName: 'Frank', rating: 5, title: 'Perfect for sensitive skin', body: 'My reactive skin loves this. I wake up with calm, hydrated skin every time.', createdAt: '2023-11-05' },
    ],
  },
  {
    id: '6',
    title: '24K Gold Anti-Aging Mask',
    slug: '24k-gold-anti-aging-mask',
    description: 'A luxurious peel-off mask to lift, firm, and tighten skin.',
    longDescription: 'Experience the ultimate in luxury skincare. Our 24K Gold Anti-Aging Mask is infused with pure 24K gold and powerful peptides to combat signs of aging. This peel-off mask helps to lift, firm, and tighten the skin, reducing the appearance of fine lines and wrinkles for a more youthful, radiant look.',
    price: 5500,
    currency: 'INR',
    images: ['product-6'],
    ingredients: ['24K Gold', 'Peptides', 'Collagen', 'Hyaluronic Acid'],
    benefits: ['Firms and lifts', 'Reduces wrinkles', 'Improves elasticity'],
    skinTypes: ['dry', 'normal', 'combination'],
    tags: ['anti-aging'],
    stock: 50,
    rating: 4.7,
    reviewsCount: 88,
    reviews: [],
  },
];
